export const FETCH_STALL_REQUEST = 'FETCH_STALL_REQUEST'
export const FETCH_STALL_SUCCESS = 'FETCH_STALL_SUCCESS'
export const FETCH_STALL = 'FETCH_STALL'
export const FETCH_STALL_FAILURE = 'FETCH_STALL_FAILURE'
